# Generated by Django 3.1.14 on 2024-09-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0003_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'subadmin')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=250)),
                ('productpricebd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('shippingcharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productavailability', models.CharField(max_length=50)),
                ('productimage1', models.ImageField(blank=True, upload_to='media/product_image1')),
                ('productimage2', models.ImageField(blank=True, upload_to='media/product_image2')),
                ('productimage3', models.ImageField(blank=True, upload_to='media/product_image3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.brand')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.category')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.subcategory')),
            ],
        ),
    ]
