# Generated by Django 3.1.14 on 2024-09-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_regusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'subadmin'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
                ('reguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.regusers')),
            ],
        ),
    ]
