# Generated by Django 3.1.14 on 2024-09-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0010_auto_20240915_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='tracking',
            name='remark',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='shoppingapp.order'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
