# Generated by Django 3.1.14 on 2024-09-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0012_auto_20240915_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
                ('reguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.regusers')),
            ],
        ),
    ]
