# Generated by Django 3.1.14 on 2024-09-19 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0013_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
            ],
        ),
    ]
