# Generated by Django 3.1.14 on 2024-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='news_id',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
