# Generated by Django 3.1.14 on 2024-09-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_auto_20240919_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
